# Jekyll configuration
title: RGVWEBPRO
description: >- # this means to ignore newlines until "baseurl:"
  Docs
logo: "/assets/img/logo.png"
theme: just-the-docs

# site settings
url: https://rgvwebpro.github.io

# style
color_scheme: dark

# aux links
aux_links:
  GitHub: https://github.com/rgvwebpro
